// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNnT7polW6dkhddbkpns6Zd55go0155yg',
    appId: '1:13527952383:web:f85d00b95edc4906db55ca',
    messagingSenderId: '13527952383',
    projectId: 'flutterwebrtc-a022b',
    authDomain: 'flutterwebrtc-a022b.firebaseapp.com',
    storageBucket: 'flutterwebrtc-a022b.firebasestorage.app',
    measurementId: 'G-6N9PZV5NPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMWu9nrCxZd1u4DGeg2_rLXMP0lZbuQTY',
    appId: '1:13527952383:android:00a17e56b852fcdedb55ca',
    messagingSenderId: '13527952383',
    projectId: 'flutterwebrtc-a022b',
    storageBucket: 'flutterwebrtc-a022b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnMNayOYdh20412Wo6lDhLrITpziVPHAQ',
    appId: '1:13527952383:ios:e1f9f28b37092814db55ca',
    messagingSenderId: '13527952383',
    projectId: 'flutterwebrtc-a022b',
    storageBucket: 'flutterwebrtc-a022b.firebasestorage.app',
    iosBundleId: 'com.example.flutterWebRtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnMNayOYdh20412Wo6lDhLrITpziVPHAQ',
    appId: '1:13527952383:ios:e1f9f28b37092814db55ca',
    messagingSenderId: '13527952383',
    projectId: 'flutterwebrtc-a022b',
    storageBucket: 'flutterwebrtc-a022b.firebasestorage.app',
    iosBundleId: 'com.example.flutterWebRtc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNnT7polW6dkhddbkpns6Zd55go0155yg',
    appId: '1:13527952383:web:13c2faa7cb0f3d8ddb55ca',
    messagingSenderId: '13527952383',
    projectId: 'flutterwebrtc-a022b',
    authDomain: 'flutterwebrtc-a022b.firebaseapp.com',
    storageBucket: 'flutterwebrtc-a022b.firebasestorage.app',
    measurementId: 'G-Q9PSWBXP24',
  );
}
